carplace/urls.py
from django.contrib import admin
from django.urls import path, include

#Для обработки выгруженных файлов
from django.conf import settings
from django.conf.urls.static import static

app_name = 'carplace'

urlpatterns = [
    path('', include('main.urls')),
]


if settings.DEBUG: #Этот путь нужен только если сайт работает в отладочном режиме
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.contrib import admin
from django.urls import path

from .views import *

from django.contrib.auth.views import LoginView, LogoutView

app_name = 'main'

urlpatterns = [
    #Authentication
    path('login/', user_login, name = 'login'),
    path('logout/', LogoutView.as_view(next_page='main:homepage', template_name = "logged_out.html"), name = 'logout'),
    #Homepage
    path('', homepage, name = 'homepage'),
    #All
    path('all/<str:kind>/', all, name = 'all'),
    path('all/', all, kwargs={'kind': None}, name = 'all'),
    #by_category
    path('category/<str:kind>/<str:category_id>/', by_category, name = 'by_category'),
    #Detail
    path('detail/<str:kind>/<str:object_id>/', detail, name = 'detail'),
    #Add|Edit|Delete
    path('add/<str:kind>/', add, name = 'add'),
    path('add/', add, kwargs={'kind': None}, name = 'add'),
    path('edit/<str:kind>/<str:object_id>/', edit, name = 'edit'),
    path('delete/<str:kind>/<str:object_id>/', delete, name = 'delete'),
    #Language
    path('language/change/<str:new_language>/', language_change, name = 'language_change'),
    #Moderation
    path('moderation/', moderation, name = 'moderation'),
    #Search
    path('search/<str:text>/', search_result, name = 'search_result'),
    path('search/', search_input, name = 'search_input'),
]

main/models.py
from django.db import models

from django.contrib.auth.models import User

from django.core.validators import MinValueValidator, MaxValueValidator, MinLengthValidator
from django.shortcuts import get_object_or_404
from django.http import Http404

from django.db.models.signals import pre_save, post_save, post_init
from django.contrib.auth.signals import user_logged_in
from django.dispatch import receiver

import datetime


class Offer(models.Model):
    name = models.CharField(max_length = 100)
    name_kz = models.CharField(max_length = 100, null = True, blank = True)
    description = models.CharField(max_length = 1000, null = True, blank = True)
    description_kz = models.CharField(max_length = 1000, null = True, blank = True)
    price = models.PositiveIntegerField()
    views = models.PositiveIntegerField(default = 0)

    published = models.DateTimeField(auto_now_add = True)

    class Meta:
        abstract = True


class Product(Offer):
    category = models.ForeignKey('ProductCategory', related_name = 'category', on_delete = models.CASCADE)
    in_stock = models.BooleanField()

    def __str__(self):
        return self.name


class Service(Offer):
    category = models.ForeignKey('ServiceCategory', related_name = 'category', on_delete = models.CASCADE)
    duration = models.CharField(max_length = 50)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length = 100)
    name_kz = models.CharField(max_length = 100, null = True, blank = True)
    image = models.ImageField(verbose_name = 'Изображение', null = True)

    class Meta:
        abstract = True

class ProductCategory(Category):

    def __str__(self):
        return self.name

class ServiceCategory(Category):

    def __str__(self):
        return self.name


class Client(models.Model):
    user = models.OneToOneField(User, related_name = 'client', on_delete = models.CASCADE)

@receiver(post_save, sender=User)
def user_create(sender, instance, created, **kwargs):
	if created:
		Client.objects.create(user=instance)


class Phone(models.Model):
    phone = models.CharField(max_length=12, validators=[MinLengthValidator(11)])

    def __str__(self):
        return self.phone


class Ip(models.Model):
    adress = models.CharField(max_length = 50)
    year = models.CharField(max_length = 50)
    month = models.CharField(max_length = 50)
    viewed_products = models.ManyToManyField('Product', through = "ProductView")
    viewed_services = models.ManyToManyField('Service', through = "ServiceView")


class ProductView(models.Model):
    product = models.ForeignKey('Product', on_delete = models.CASCADE)
    ip = models.ForeignKey('Ip', on_delete = models.CASCADE)

class ServiceView(models.Model):
    service = models.ForeignKey('Service', on_delete = models.CASCADE)
    ip = models.ForeignKey('Ip', on_delete = models.CASCADE)


class Search(models.Model):
    text = models.CharField(max_length = 100)

main/forms.py
from django import forms
from .models import *

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django.core import validators
from django.core.validators import FileExtensionValidator


class ProductCategoryForm(forms.ModelForm):
	name = forms.CharField(label = 'Название на русском')
	name_kz = forms.CharField(label = 'Название на казахском')
	image = forms.ImageField(label = 'Изображение', validators=[FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], error_messages={'invalid_extension' : 'Этот формат не поддерживается', 'required' : ''}, required = True)

	class Meta:
		model = ProductCategory
		fields = ('name', 'name_kz', 'image',)


class ServiceCategoryForm(forms.ModelForm):
	name = forms.CharField(label = 'Название на русском')
	name_kz = forms.CharField(label = 'Название на казахском')
	image = forms.ImageField(label = 'Изображение', validators=[FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], error_messages={'invalid_extension' : 'Этот формат не поддерживается', 'required' : ''}, required = True)

	class Meta:
		model = ServiceCategory
		fields = ('name', 'name_kz', 'image',)


class ProductForm(forms.ModelForm):
	category = forms.ModelChoiceField(queryset = ProductCategory.objects.all(), label = "Категория", empty_label = None, error_messages={'required': 'Выберите категорию'}, widget=forms.widgets.Select(attrs={'size': 8}))
	name = forms.CharField(label = 'Название на русском')
	name_kz = forms.CharField(label = 'Название на казахском')
	description = forms.CharField(label = 'Описание на русском', widget=forms.widgets.Textarea())
	description_kz = forms.CharField(label = 'Описание на казахском', widget=forms.widgets.Textarea())
	price = forms.IntegerField(label = 'Цена')
	in_stock = forms.BooleanField(label = 'Есть в наличии')

	class Meta:
		model = Product
		fields = ('category', 'name', 'name_kz', 'description', 'description_kz', 'price', 'in_stock',)


class ServiceForm(forms.ModelForm):
	category = forms.ModelChoiceField(queryset = ServiceCategory.objects.all(), label = "Категория", empty_label = None, error_messages={'required': 'Выберите категорию'}, widget=forms.widgets.Select(attrs={'size': 8}))
	name = forms.CharField(label = 'Название на русском')
	name_kz = forms.CharField(label = 'Название на казахском')
	description = forms.CharField(label = 'Описание', widget=forms.widgets.Textarea())
	description_kz = forms.CharField(label = 'Описание на казахском', widget=forms.widgets.Textarea())
	price = forms.IntegerField(label = 'Цена')
	duration = forms.IntegerField(label = 'Время выполнения (мин)')

	class Meta:
		model = Service
		fields = ('category', 'name', 'name_kz', 'description', 'description_kz', 'price', 'duration',)


class PhoneForm(forms.ModelForm):
	phone = forms.CharField(label = '')

	class Meta:
		model = Phone
		fields = ('phone',)


class SearchForm(forms.ModelForm):
	text = forms.CharField(label = '')

	class Meta:
		model = Search
		fields = ('text',)


class LoginForm(forms.Form):
	username = forms.CharField(label = 'Ваш никнейм')
	password = forms.CharField(label = 'Ваш пароль', widget=forms.PasswordInput)

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User, UserManager
from django.contrib.auth.forms import UserCreationForm

from .models import *
from .forms import *

import time
import datetime
import requests
import telegram

from django.contrib.auth import authenticate, login
from django.contrib.auth.views import redirect_to_login
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import HttpResponseRedirect, HttpRequest, HttpResponseForbidden, HttpResponse, HttpResponseNotFound, Http404
from django.urls import reverse

from django.template import RequestContext

from django.core.paginator import Paginator
from django.core.mail import send_mail


def homepage(request):
    p_categories = ProductCategory.objects.all()
    s_categories = ServiceCategory.objects.all()

    products = Product.objects.order_by('-views')[:6]
    services = Service.objects.order_by('-views')[:6]

    adress = request.META.get('HTTP_X_FORWARDED_FOR')
    if adress:
        adress = adress.split(',')[-1].strip()
    else:
        adress = request.META.get('REMOTE_ADDR')

    try:
        ip = Ip.objects.get(adress = adress, year = str(datetime.datetime.now().year), month = str(datetime.datetime.now().month))
    except Ip.DoesNotExist:
        Ip.objects.create(adress = adress, year = str(datetime.datetime.now().year), month = str(datetime.datetime.now().month))

    language = request.COOKIES.get('language')
    if not language:
        language = 'ru'

    context = {'language' : language, 'p_categories' : p_categories, 's_categories' : s_categories, 'products' : products, 'services' : services}
    response = render(request, 'homepage.html', context)
    response.set_cookie('language', language)
    return response


def all(request, kind):
    p_categories = ProductCategory.objects.all()
    s_categories = ServiceCategory.objects.all()

    language = request.COOKIES.get('language')
    if not language:
        language = 'ru'

    if kind == 'products':
        objects = Product.objects.order_by('-published')
    elif kind == 'services':
        objects = Service.objects.order_by('-published')
    elif kind == 'p_categories' or kind == 's_categories':
        template = 'all.html'
        context = {'language' : language, 'p_categories' : p_categories, 's_categories' : s_categories, 'kind' : kind}
    else:
        context = {'language' : language, 'p_categories' : p_categories, 's_categories' : s_categories}
        template = 'all_choose.html'

    if kind == 'products' or kind == 'services':
        paginator = Paginator(objects, 6)
        if 'page' in request.GET:
            page_num = request.GET['page']
        else:
            page_num = 1
        page = paginator.get_page(page_num)
        context = {'language' : language, 'p_categories' : p_categories, 's_categories' : s_categories, 'kind' : kind, 'objects' : page.object_list, 'page' : page}
        template = 'all.html'


    response = render(request, template, context)
    response.set_cookie('language', language)
    return response


def by_category(request, kind, category_id):
    p_categories = ProductCategory.objects.all()
    s_categories = ServiceCategory.objects.all()

    language = request.COOKIES.get('language')
    if not language:
        language = 'ru'

    if kind == 'products':
        category = get_object_or_404(ProductCategory, id = category_id)
        objects = Product.objects.filter(category = category)
    elif kind == 'services':
        category = get_object_or_404(ServiceCategory, id = category_id)
        objects = Service.objects.filter(category = category)
    else:
        return HttpResponseNotFound()

    paginator = Paginator(objects, 6)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)

    context = {'language' : language, 'p_categories' : p_categories, 's_categories' : s_categories, 'category' : category, 'kind' : kind, 'objects' : page.object_list, 'page' : page}
    response = render(request, 'by_category.html', context)
    response.set_cookie('language', language)
    return response



def detail(request, kind, object_id):
    p_categories = ProductCategory.objects.all()
    s_categories = ServiceCategory.objects.all()

    language = request.COOKIES.get('language')
    if not language:
        language = 'ru'

    if kind == 'services':
        object = get_object_or_404(Service, id = object_id)
    else:
        object = get_object_or_404(Product, id = object_id)

    context = {'language' : language, 'p_categories' : p_categories, 's_categories' : s_categories, 'object' : object, 'kind' : kind}
    response = render(request, 'detail.html', context)
    response.set_cookie('language', language)
    return response


def add(request, kind):
    if request.user.is_staff:
        p_categories = ProductCategory.objects.all()
        s_categories = ServiceCategory.objects.all()

        language = request.COOKIES.get('language')
        if not language:
            language = 'ru'

        if kind == 'products':
            form_type = ProductForm
        elif kind == 'services':
            form_type = ServiceForm
        elif kind == 'p_categories':
            form_type = ProductCategoryForm
        elif kind == 's_categories':
            form_type = ServiceCategoryForm
        else:
            context = {'language' : language, 'p_categories' : p_categories, 's_categories' : s_categories}
            response = render(request, 'add_choose.html', context)
            response.set_cookie('language', language)
            return response

        if request.method == "POST":
            f = form_type(request.POST, request.FILES)
            if f.is_valid():
                f = f.save(commit = False)
                f.save()
                return HttpResponseRedirect(reverse('main:all', args = (kind,)))
            else:
                context = {'language' : language, 'p_categories' : p_categories, 's_categories' : s_categories, 'kind' : kind, 'form' : f}
                response = render(request, 'add.html', context)
                response.set_cookie('language', language)
                return response
        else:
            f = form_type()
            context = {'language' : language, 'p_categories' : p_categories, 's_categories' : s_categories, 'kind' : kind, 'form' : f}
            response = render(request, 'add.html', context)
            response.set_cookie('language', language)
            return response
    else:
        return HttpResponseNotFound()


def edit(request, kind, object_id):
    language = request.COOKIES.get('language')
    if not language:
        language = 'ru'

    if request.user.is_staff:
        p_categories = ProductCategory.objects.all()
        s_categories = ServiceCategory.objects.all()

        if kind == 'products':
            form_type = ProductForm
            object = get_object_or_404(Product, id = object_id)

        elif kind == 'services':
            form_type = ServiceForm
            object = get_object_or_404(Service, id = object_id)

        elif kind == 'p_categories':
            form_type = ProductCategoryForm
            object = get_object_or_404(ProductCategory, id = object_id)

        elif kind == 's_categories':
            form_type = ServiceCategoryForm
            object = get_object_or_404(ServiceCategory, id = object_id)

        else:
            return HttpResponseNotFound()

        if request.method == "POST":
            f = form_type(request.POST, request.FILES, instance = object)
            if f.is_valid():
                f = f.save(commit = False)
                f.save()
                if kind == 'products' or kind == 'services':
                    return HttpResponseRedirect(reverse('main:detail', args = (kind, object_id,)))
                else:
                    return HttpResponseRedirect(reverse('main:all', args = (kind,)))
            else:
                context = {'language' : language, 'p_categories' : p_categories, 's_categories' : s_categories, 'object_id' : object_id, 'kind' : kind, 'form' : f}
                response = render(request, 'add.html', context)
                response.set_cookie('language', language)
                return response
        else:
            f = form_type(instance = object)
            context = {'language' : language, 'p_categories' : p_categories, 's_categories' : s_categories, 'object_id' : object_id, 'kind' : kind, 'form' : f}
            response = render(request, 'add.html', context)
            response.set_cookie('language', language)
            return response
    else:
        return HttpResponseNotFound()


def delete(request, kind, object_id):
    language = request.COOKIES.get('language')
    if not language:
        language = 'ru'

    if request.user.is_staff:
        if kind == 'products':
            object = get_object_or_404(Product, id = object_id)

        elif kind == 'services':
            object = get_object_or_404(Service, id = object_id)

        elif kind == 'p_categories':
            object = get_object_or_404(ProductCategory, id = object_id)
            if object.image:
                object.image.delete()

        elif kind == 's_categories':
            object = get_object_or_404(ServiceCategory, id = object_id)
            if object.image:
                object.image.delete()
        else:
            return HttpResponseNotFound()

        if kind == 'products' or kind == 'services' or kind == 'p_categories' or kind == 's_categories':
            object.delete()

        return HttpResponseRedirect(reverse('main:all', args = (kind,)))
    else:
        return HttpResponseNotFound()


def moderation(request):
    language = request.COOKIES.get('language')
    if not language:
        language = 'ru'

    if request.user.is_staff:
        p_categories = ProductCategory.objects.all()

main/templates/502.html
{% extends "base.html" %}
{% block content %}

   <div class="container">
        <br/>
        <h2>Внутренняя ошибка сервера. Попробуйте зайти чуть позже. | Внутренняя ошибка сервера. | Server error</h2>
        <br/>
        <hr/>
    </div>

{% endblock %}

main/templates/add_choose.html
{% extends "base.html" %}
{% block content %}
{% load static %}

   <!-- ADD -->
   <div class="album py-5 bg-light">
     <div class="container text-center">
          <h3>
          {% if language == 'kz' %}
          <a href="{% url 'main:add' 'products' %}" class="btn btn-primary" style="margin: 5px">Элементті қосыңыз</a>
          <a href="{% url 'main:add' 'services' %}" class="btn btn-primary" style="margin: 5px">Қызметті қосу</a>
          <a href="{% url 'main:add' 'p_categories' %}" class="btn btn-primary" style="margin: 5px">Өнім санатын қосыңыз</a>
          <a href="{% url 'main:add' 's_categories' %}" class="btn btn-primary" style="margin: 5px">Қызметтер санатын қосыңыз</a>
          {% else %}
          <a href="{% url 'main:add' 'products' %}" class="btn btn-primary" style="margin: 5px">Добавить товар</a>
          <a href="{% url 'main:add' 'services' %}" class="btn btn-primary" style="margin: 5px">Добавить услугу</a>
          <a href="{% url 'main:add' 'p_categories' %}" class="btn btn-primary" style="margin: 5px">Добавить категорию товара</a>
          <a href="{% url 'main:add' 's_categories' %}" class="btn btn-primary" style="margin: 5px">Добавить категорию услуг</a>
          {% endif %}
          </h3>
      </div>
    </div>

{% endblock %}

main/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>CarPlace</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" />
    <!-- Google Fonts Roboto -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" />
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}" />
    <!-- Custom styles -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

</head>
<body>
  <header>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
      <div class="container-fluid">
        <a class="navbar-brand" target="_blank" href="{% url 'main:homepage' %}">
          <img src="{% static 'img/carplacelogo.png' %}" height=50 alt="" loading="lazy"
            style="margin-top: -3px;" />
        </a>
        <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarExample01"
          aria-controls="navbarExample01" aria-expanded="false" aria-label="Toggle navigation">
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarExample01">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if language == 'kz' %}
            <li class="nav-item ">
              <a class="nav-link" href="{% url 'main:language_change' 'ru' %}" rel="nofollow">RU</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" aria-current="page" href="{% url 'main:homepage' %}">Басты бет</a>
            </li>
            <li class="nav-item ">
              <a class="nav-link" href="{% url 'main:all' 'products' %}" rel="nofollow">Тауарлар</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:all' 'services' %}">Қызметтер</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:all' 'p_categories' %}">Санаттар</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:search_input' %}">Іздеу</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:add' %}">Қосу</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:moderation' %}">Модерация</a>
            </li>
            {% else %}
            <li class="nav-item ">
              <a class="nav-link" href="{% url 'main:language_change' 'kz' %}" rel="nofollow">KZ</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" aria-current="page" href="{% url 'main:homepage' %}">Главная</a>
            </li>
            <li class="nav-item ">
              <a class="nav-link" href="{% url 'main:all' 'products' %}" rel="nofollow">Товары</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:all' 'services' %}">Услуги</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:all' 'p_categories' %}">Категории</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:search_input' %}">Поиск</a>
            </li>
            {% if request.user.is_staff %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:add' %}">Добавить</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:moderation' %}">Модерация</a>
            </li>
            {% endif %}
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </header>

  {% block content %}
  {% endblock %}

  <!-- FOOTER -->
  <footer class="text-muted">
      <div class="container">
          <p class="float-right">
          <a href="#"></a>
          </p>
          <p>CarPlace | +7-778-859-00-69 | Б. Момышұлы 9Б </p>
      </div>
  </footer>

  <!-- JS -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</body>
</html>

main/templates/detail.html
{% extends "base.html" %}

{% block head %}
<title>CarPlace | {{ object.name }}</title>
<meta name="description" content="{{ object.name }} {{ object.description }}">
{% endblock %}

{% block content %}
{% load thumbnail %}
{% load static %}

    <!-- DETAIL -->
    <div class="album py-5 bg-light">
       <div class="container">

       <div class="row align-items-md-stretch">
           <div class="col-md-6">
                <img class="card-img-top p-4 bg-dark rounded-3 carousel slide" src="{{ object.category.image|thumbnail_url:'main' }}" alt="" />
           </div>
           <div class="col-md-6">
             <div class="h-100 p-5 bg-light border rounded-3">

             {% if language == 'kz' and object.name_kz and object.description_kz and object.category.name_kz %}
                  <h1 class="display-4 font-weight-normal">{{ object.name_kz }}</h1>
                  <hr/>
                  <h3 class="display-6 font-weight-light">{{ object.price }}₸</h3>
                  <hr/>
                  <p class="lead font-weight-normal">{{ object.category.name_kz }}</p>
                  <hr/>

                  {% if object.in_stock %}
                  {% if object.in_stock == True %}
                  <p class="lead font-weight-normal">Қоймада бар</p>
                  {% else %}
                  <p class="lead font-weight-normal">Қоймада жоқ</p>
                  {% endif %}
                  {% endif %}

                  {% if object.duration %}
                  <p class="lead font-weight-normal">Жұмыс уақыты: {{ object.duration }} мин.</p>
                  {% endif %}

                  {% if request.user.is_staff %}
                  <a class="btn btn-outline-secondary" href="{% url 'main:delete' kind object.pk %}">Жою</a>
                  <a class="btn btn-outline-secondary" href="{% url 'main:edit' kind object.pk %}">Өзгерту</a>
                  {% endif %}
                  <hr/>
             {% else %}
                  <h1 class="display-4 font-weight-normal">{{ object.name }}</h1>
                  <hr/>
                  <h3 class="display-6 font-weight-light">{{ object.price }}₸</h3>
                  <hr/>
                  <p class="lead font-weight-normal">{{ object.category.name }}</p>
                  <hr/>

                  {% if object.in_stock %}
                  {% if object.in_stock == True %}
                  <p class="lead font-weight-normal">Есть в наличии</p>
                  {% else %}
                  <p class="lead font-weight-normal">Нет в наличии</p>
                  {% endif %}
                  {% endif %}

                  {% if object.duration %}
                  <p class="lead font-weight-normal">Время выполнения: {{ object.duration }}</p>
                  {% endif %}

                  {% if request.user.is_staff %}
                  <a class="btn btn-outline-secondary" href="{% url 'main:delete' kind object.pk %}">Удалить</a>
                  <a class="btn btn-outline-secondary" href="{% url 'main:edit' kind object.pk %}">Изменить</a>
                  {% endif %}
                  <hr/>
             {% endif %}
             </div>
           </div>
       </div>

       </div>
    </div>
    <br/>

    <div class="album py-5 bg-light">
       <div class="container">

          <div class="col-md">
            <div class="h-100 p-5 bg-light border rounded-3">
              {% if language == 'kz' and object.name_kz and object.description_kz %}
                  <p class="lead font-weight-normal">{{ object.description_kz }}</p>
              {% else %}
                  <p class="lead font-weight-normal">{{ object.description }}</p>
              {% endif %}
            </div>
          </div>

       </div>
    </div>


{% endblock %}

main/templates/logged_out.html
{% extends "base.html" %}
{% block content %}

   <!-- LOGGED_OUT -->
    <div class="container">
        <h4>Вы вышли из аккаунта | Сіз есептік жазбадан шықтыңыз</h4>
    </div>

{% endblock %}

main/templates/login.html
{% extends "base.html" %}
{% block content %}

   <!-- LOGIN -->
   <div class="album py-5 bg-light">
     <div class="container">
     <div class="row">

       {% load crispy_forms_tags %}
       {% if request.user.is_authenticated %}

       <div class="col-md-5 p-lg-5 mx-auto my-5">
         {% if language == 'kz' %}
         <h1 class="display-4 font-weight-normal text-center">Сіз әлдеқашан жүйеге кірдіңіз</h1>
         {% else %}
         <h1 class="display-4 font-weight-normal text-center">Вы уже вошли в аккаунт</h1>
         {% endif %}
          <hr/>
          <div class="text-center">
              {% if language == 'kz' %}
              <a class="btn btn-outline-secondary" href="{% url 'main:logout' %}">Шығару</a>
              {% else %}
              <a class="btn btn-outline-secondary" href="{% url 'main:logout' %}">Выйти</a>
              {% endif %}
          </div>
          <br/>
       </div>
       {% else %}
       <form method="post" class="form-signin">
           {% if language == 'kz' %}
           <h1 class="h3 mb-3 font-weight-normal">Кіру</h1>
           {% else %}
           <h1 class="h3 mb-3 font-weight-normal">Авторизация</h1>
           {% endif %}

           {% csrf_token %}
           {{ form|crispy }}
           <br/>
           <input type="hidden" name="next" value="{{ request.GET.next }}">
           <input class="btn btn-outline-secondary" type="submit" value="Войти | Кіру">
       </form>
       {% endif %}

     </div>
     </div>
   </div>

{% endblock %}

main/templates/moderation.html
{% extends "base.html" %}
{% block content %}

   <!-- LOGGED_OUT -->
    <div class="container">
      <br/>
      {% if language == 'kz' %}
        <h4>Бір айдағы көріністер - {{ views }}</h4>
      {% else %}
        <h4>Просмотров за месяц - {{ views }}</h4>
      {% endif %}
    </div>

{% endblock %}